@startuml Parcours_02
title Parcours Client


start
:page d'accueil;
:Authentification;
:Liste des pizza;
fork
    :afficher les parametres;
    fork
        :mofifier magasin et coordonnées;
    fork again
        :afficher historique des commandes;
        :afficher le status d'une commande;
        end
    endfork
fork again
:afficher détail pizza;
fork again
:ajouter au panier;
fork again
:voir le panier;
endfork


@enduml