@startuml Parcours_01
title Parcours sans authentification


start
:page d'accueil;
fork
    :Choisir magasin;
fork again
    :Authentification;
    stop
end fork
:Liste des pizza;
:info pizza;


@enduml