@startuml 03_authentification
title Diagramme de cas d'utilisation *Authentification*

package Authentification{
    (S'identifier)
    (Choisir une boutique)
    (Creer un compte)
}
package Commande
package Produit

Commande -l- Authentification
Produit -u- Authentification
@enduml


