@startuml 03_commande
title Diagramme de package *Commande*

actor Gestionnaire_de_commande as GESTCMD
actor Client as CUSTOMER
actor Banque <<include>> as BANK
actor Pizzaiolo as PZLO

package Commandes{
    ' left to right direction
    (Gérer les commandes) as CMD
    (receptionner une commande)
    (préparer une commande)
    (livrer une commande)
    (Suivre l'état d'une commande)
    (Modifier ou annuler une commande)
    (Payer une commande)
}

CUSTOMER <|-- GESTCMD
CUSTOMER - CMD
CMD -- PZLO
CMD - BANK


@enduml