@startuml 03_produit
title Diagramme de cas d'utilisation *Produit*

actor Gestionnaire_de_stock as GESTSTOCK
actor Pizzaiolo as PZLO

package Produit{
    (Gérer le stock) as STOCK
    (Gérer le recettes) as RECIPE
}

STOCK - RECIPE
GESTSTOCK -u- STOCK
RECIPE -- PZLO

@enduml