@startuml 01_contexte
title Diagramme de contexte

rectangle OC_Pizza {
}

    actor Gestionnaire_de_commande as GESTCMD
    actor Client as CUSTOMER
    actor Gestionnaire_de_stock as GESTSTOCK
    actor Pizzaiolo as PZLO
    actor Banque <<system>> as BANK
    actor Responsable as BOSS




GESTSTOCK - OC_Pizza
PZLO -- OC_Pizza
BOSS -- OC_Pizza
OC_Pizza - BANK
OC_Pizza -- CUSTOMER
OC_Pizza -- GESTCMD

@enduml