@startuml 03_ingredient
title Diagramme de cas d'utilisation *Ingredient*

' actor Gestionnaire_de_commande as GESTCMD
' actor Client as CUSTOMER
actor Gestionnaire_de_stock as GESTSTOCK
' actor Pizzaiolo as PZLO
actor Responsable as BOSS
' actor Banque <<system>> as BANK

package Ingredient{
    (Gérer le stock) as STOCK
    (Gérer les ingrédients) as ITEMS
}

ITEMS -- BOSS
STOCK -- GESTSTOCK

@enduml