@startuml 03_authentification
title Diagramme de cas d'utilisation *authentification*

actor Gestionnaire_de_commande as GESTCMD
' actor Client as CUSTOMER
' actor Gestionnaire_de_stock as GESTSTOCK
' actor Pizzaiolo as PZLO
actor Responsable as BOSS
' actor Banque <<system>> as BANK

package authentification{
    left to right direction
    (creer un compte) as REGISTER
    (gérer le personnel) as MANAGE_EMPL
    (s'identifier) as LOGIN
    (gérer les boutiques) as STORE
}
MANAGE_EMPL -> REGISTER: <<extend>>
CUSTOMER -- REGISTER
GESTCMD -|> CUSTOMER
BOSS -- MANAGE_EMPL
BOSS -- STORE
Tous_les_utilisateurs -- LOGIN

@enduml


