@startuml 0_ListActors
title <u>Liste des acteurs</u>

actor client as CUSTOMER

rectangle Boutique {
    actor Pizzaiolo as PIZLO
    actor gestionnaire_stock as GEST
    actor personnel_accueil as ACCUEIL
}

rectangle Service_externe {
    actor Banque <<System>> as BANK
}

@enduml