@startuml 2_Commande_UseCaseDiagram

title <u>Commande cas d'utilisation</u>

actor Pizzaiolo as PIZLO
actor personnel_accueil as ACCUEIL
actor client as CUSTOMER
actor Banque <<System>> as BANK

' COMMANDES
package Commandes {
    left to right direction
    rectangle Read_C {
        (lister les commades) AS LIST_CMD
    }
    rectangle Create_C {
        (créer une commande) AS CREATE_CMD
    }
    rectangle Update_C {
        (payer) AS PAY_CMD
        (modifier l'état d'une commande) AS MODIFY_STATE_CMD
        (voir l'etat d'une commande) AS SHOW_STATE_CMD
        (annuler une commande) AS CANCEL_CMD
    }
    rectangle Delete_C {
    }
}
CUSTOMER <|- ACCUEIL

PAY_CMD --> MODIFY_STATE_CMD
CANCEL_CMD --> SHOW_STATE_CMD
SHOW_STATE_CMD -> MODIFY_STATE_CMD

PIZLO --> LIST_CMD
PIZLO -> MODIFY_STATE_CMD

CUSTOMER --> CREATE_CMD

CUSTOMER --> CANCEL_CMD
CUSTOMER --> PAY_CMD
BANK <.r. PAY_CMD
BANK ..> MODIFY_STATE_CMD


@enduml