@startuml 2_Ingredient_UseCaseDiagram

title <u>Ingredient cas d'utilisation</u>

left to right direction

actor gestionnaire_stock as GEST

' INGREDIENTS
package ingrédients_stock {
    rectangle Create_S{
    }
    rectangle Read_S {
        (consulter le stock d'ingrédient) AS SHOW_ITEM
    }
    rectangle Update_S {
        (définir le stock) AS SET_ITEN
    }
    rectangle Delete_S{
    }
}

GEST --> SET_ITEN
GEST --> SHOW_ITEM

@enduml