@startuml  2_Responsable_UseCaseDiagram

title <u>Diagramme d'utilisation Responsable</u>

actor Responsable as RESP

'COMMANDES
    (lister les commandes) AS LIST_CMD

' RECETTE
    (rédiger une recette) AS CREATE_RECIPE
    (consulter la liste des recettes) AS LIST_RECIPE
    (consulter une recette) AS SHOW_RECIPE
    (modifier une recette) AS MODIFY_RECIPE
    (supprimer une recette) AS DEL_RECIPE

' INGREDIENTS
    (créer un ingrédient) AS CREATE_ITEM
    (consulter la liste d'ingrédients) AS LIST_ITEM

RESP - LIST_CMD

' RESP -- CREATE_RECIPE
RESP -- LIST_RECIPE
LIST_RECIPE -- MODIFY_RECIPE
LIST_RECIPE -- SHOW_RECIPE
LIST_RECIPE - DEL_RECIPE
CREATE_RECIPE - LIST_RECIPE
' RESP -r- CREATE_ITEM
CREATE_ITEM -- LIST_ITEM
RESP -l- LIST_ITEM
LIST_ITEM .. CREATE_RECIPE

@enduml