@startuml 2_Recette_UseCaseDiagram

title <u>Recette cas d'utilisation</u>

left to right direction

actor Pizzaiolo as PIZLO
actor client as CUSTOMER

' RECETTE
package Pizza_Recette {
    rectangle Ceate_R {
    }
    rectangle Read_R {
        (consulter la liste des recettes) AS LIST_RECIPE
        (consulter une recette) AS SHOW_RECIPE
    }
    rectangle Update_R {
    }
    rectangle Delete_R {
    }
}


CUSTOMER --> LIST_RECIPE
PIZLO --> SHOW_RECIPE

@enduml