@startuml 3_Commande_PackageDiagram

title <u>Commande PackageDiagram</u>

actor Responsable as RESP
actor Pizzaiolo as PIZLO
actor personnel_accueil as ACCUEIL
actor client as CUSTOMER
actor Banque <<System>> as BANK

' COMMANDES
package Commandes {
    left to right direction
    rectangle Create_C {
        (créer une commande) AS CREATE_CMD
        (Ecrire un commentaire) AS COMMENT_CMD
        (modifier la recette) AS CUSTO_CMD
    }
    rectangle Read_C {
        (voir l'etat d'une commande) AS SHOW_STATE_CMD
        (lister les commades) AS LIST_CMD
    }
    rectangle Update_C {
        (modifier l'état d'une commande) AS MODIFY_STATE_CMD
        (annuler une commande) AS CANCEL_CMD
        (payer sur place) AS PAY_STORE_CMD
        (payer en ligne) AS PAY_ONLINE_CMD
    }
    rectangle Delete_C {
        
    }
}

PAY_ONLINE_CMD --> MODIFY_STATE_CMD
PAY_STORE_CMD --> MODIFY_STATE_CMD
CANCEL_CMD --> MODIFY_STATE_CMD

RESP --> LIST_CMD
PIZLO -l-> LIST_CMD
PIZLO --> MODIFY_STATE_CMD
ACCUEIL --> CREATE_CMD
ACCUEIL --> COMMENT_CMD
ACCUEIL --> CUSTO_CMD
ACCUEIL --> SHOW_STATE_CMD
ACCUEIL --> LIST_CMD
ACCUEIL --> CANCEL_CMD
CUSTOMER --> CREATE_CMD
CUSTOMER --> COMMENT_CMD
CUSTOMER --> CUSTO_CMD
CUSTOMER --> SHOW_STATE_CMD
CUSTOMER --> CANCEL_CMD
CUSTOMER --> PAY_STORE_CMD
CUSTOMER --> PAY_ONLINE_CMD
BANK <.r. PAY_ONLINE_CMD
BANK ..> MODIFY_STATE_CMD

@enduml