@startuml 4_Commande_CANCEL_CMD_ActivityDiagram

title Annuler une commande

note: client

start

:l'utilisateur a fait une commande avec son compte et n'a pas payé en ligne;
if(la commande a commencé à être prise en compte) then (oui)
    end
else (non)
    :demander l'annulation de la commande;

stop

@enduml