@startuml 4_Ingredient_LIST_ITEM_ActivityDiagram

title consulter la liste d'ingrédients

note :Gestionnaire_stock

start

:aller dans la partie de gestion du stock;

if (le gestionnaire reste sur sa boutique par défaut) then (oui)
else (non)
    :changer de boutique;
    :choisir une boutique dans la liste;
endif
stop



start
note: Responsable
:Demander à voir la liste des ingrédients dans la partie admin;
stop

@enduml