@startuml 02_packages
title Diagramme de packages


actor Gestionnaire_de_commande as GESTCMD
actor Client as CUSTOMER
actor Gestionnaire_de_stock as GESTSTOCK
actor Pizzaiolo as PZLO
actor Banque <<include>> as BANK

rectangle OC_Pizza{
    left to right direction
    package Commandes
    package Produit
    package Authentification
}

Authentification -- Commandes
Produit -- Authentification
Commandes - Produit

CUSTOMER -- Commandes
GESTCMD -- Commandes
PZLO -- Produit
GESTSTOCK -- Produit
Commandes -- BANK


@enduml