@startuml 03_authentification
title Diagramme de cas d'utilisation *Authentification*

package Authentification{
    (S'identifier) as LOGIN
    (Créer un compte) as CREATE_LOGIN
    (Selectionner un client) as SELECT_CUSTOMER
    (Selectionner une boutique) as SELECT_STORE
    (Renseigner une adresse de livraison) as SET_DELIVER_ADRESS
}

LOGIN <-- CREATE_LOGIN : <<extend>>
LOGIN <-- SELECT_STORE : <<extend>>
LOGIN <-- SELECT_CUSTOMER : <<extend>>
LOGIN <-- SET_DELIVER_ADRESS : <<extend>>

@enduml


