@startuml 1_PackageDiagram
title <u> Diagramme de packages</u>
' left to right direction
' top to bottom direction

rectangle OC_Pizza {
    rectangle Ingredient AS ITEM
    rectangle Recette AS RECIPE
    rectangle Commande AS CMD
}

actor Pizzaiolo as PIZLO

actor Banque <<System>> as BANK
actor personnel_accueil as ACCUEIL
actor client as CUSTOMER
actor gestionnaire_stock as GEST


CMD - RECIPE
RECIPE - ITEM

PIZLO -- RECIPE
PIZLO -- CMD

CMD -l- BANK

ITEM - GEST

CUSTOMER -u- CMD
CUSTOMER -u- RECIPE

CMD -- ACCUEIL

@enduml