@startuml 4_commande_custom
title Personalisation d'une commande


:La pizza est selectionnée, la personne faisant la commande souhaite la personaliser;
start
:la liste des ingrédients présents et modifiable sont identifiés;
:une liste d'ungrédients ajoutable est identifié avec un prix;
:il y a un champ commentaire pour laisser un message au pizaiolo;
:la personne enregistre les modification;

stop

@enduml