@startuml 4_Ingredient_CREATE_ITEM_ActivityDiagram

title Creer ingredient

note: Responsable
start
:demander la création d'un nouvel ingrédient;
:remplir les caractéristiques de l'ingrédient;
:enregistrer;
stop



@enduml
