@startuml 4_Recette_CREATE_RECIPE_activityDiagram

title Creation d'une recette

note: Responsable

start

:aller dans la partie recette de la partie admin;

:la liste des recettes s'affiche;

:creer nouvelle recette;

:remplir les divers champs (désignation, prix, etc...);

repeat
if (l'ingredient est dans la liste) then (non)
    :passer dans la section creer un ingrédient;
else (oui)
endif

:ajouter l'ingrédient;

repeat while (renseigner la quantité à utiliser)

:enregistrer la recette;

:retour sur la liste des recette;

stop

@enduml