@startuml 5_DeployementDiagram

title Diagramme de déploiement

actor Humain
agent Browser

cloud {
    node ServeurWeb{
        component ApplicationDjango
    }
    database PostgreSQL
}

node Banque

Humain - Browser
Browser - ApplicationDjango
ApplicationDjango -- PostgreSQL
ApplicationDjango --Banque
Browser -- Banque 

@enduml