@startuml 4_Ingredient_SET_ITEM_ActivityDiagram

title définir le stock d'un ingrédient

note : Gestionnaire_stock

start

:aller dans la partie de gestion du stock;

if (le gestionnaire reste sur sa boutique par défaut) then (oui)
else (non)
    :changer de boutique;
    :choisir une boutique dans la liste;
endif

repeat:Selectionner un ingrédient dans la liste des ingrédients;

:entrer la nouvelle valeur de stock recu;

repeat while (enregistrer)

stop

@enduml