@startuml 2_Banque_UserCaseDiagram

title <u>Diagramme d'utilisation Banque</u>

actor Banque <<System>> as BANK

'COMMANDES
    (modifier l'état d'une commande) AS MODIFY_STATE_CMD
    (payer en ligne) AS PAY_ONLINE_CMD

' RECETTE

' INGREDIENTS

PAY_ONLINE_CMD - BANK
PAY_ONLINE_CMD -- MODIFY_STATE_CMD

@enduml